pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("iagocotta/kube-news:${env.BUILD_ID}",'-f ./src/Dockerfile ./kube-news/src')
                }
            }
        }
    }
}